apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:                           # Add spec section here
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%       # Ensure at least 75% of the pods are available during updates
      maxSurge: 1               # Only add 1 pod at a time above the desired replicas
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.2
        ports:
        - containerPort: 80